### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by iMartyn** [maximumstock/poe-currency-flip-planner#245]
The current version specified in `requirements.txt` of `typed-ast` unfortunately doesn't build on current 3.8.

I ran in docker for ease of reproducability, here's the Dockerfile :

```
FROM python:3.8-buster
RUN git clone https://github.com/maximumstock/poe-currency-flip-planner.git
RUN cd poe-currency-flip-planner ; pip install -r requirements.txt
```
And the error is 
```
    ast3/Python/ast.c:22:1: error: conflicting types for ‘_PyObject_FastCall’
     _PyObject_FastCall(PyObject *func, PyObject *const *args, int nargs)
     ^~~~~~~~~~~~~~~~~~
    In file included from /usr/local/include/python3.8/abstract.h:837,
                     from /usr/local/include/python3.8/Python.h:147,
                     from ast3/Python/ast.c:6:
    /usr/local/include/python3.8/cpython/abstract.h:145:1: note: previous definition of ‘_PyObject_FastCall’ was here
     _PyObject_FastCall(PyObject *func, PyObject *const *args, Py_ssize_t nargs)
     ^~~~~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
```

From looking at various error reports all over e.g. https://github.com/python/typed_ast/issues/124 and https://github.com/ethereum/py-evm/issues/1872, I guess this indicates a requirement to update both typed-ast and mypy.

Changing 3.8 to 3.7 works fine, at least for build.

**Comment by maximumstock** [comment]
Thank you for reaching out! I pushed a fix in https://github.com/maximumstock/poe-currency-flip-planner/commit/2eea1e67e51612e0e929d5bed3efefba7f7c689a and re-ran your `Dockerfile` with success :).

**Comment by iMartyn** [comment]
Thanks! Confirmed working from my side too (made 5 Chaos on first trade... happy customer!)

**Comment by maximumstock** [comment]
Haha, I'm glad it works :)
